title: alex laughnan
email: alex@alexlaughnan.com
description: >-
  hufflepuff. software engineer at box. queer (he/him).
  en/fr.
baseurl: ""
url: ""
twitter_username: laughnan
github_username:  laughnan
google_analytics: UA-29616781-12
theme: jekyll-theme-cayman
plugins:
  - jekyll-feed
  
